algoritmo "capital do Brasil"
// Criar um algoritmo que permita ao aluno responder
   // qual a capital do Brasil. Todas as possibilidades
    // deverão ser pensadas.
var
   Resposta:caracter
   
inicio

     escreval(" Qual é a Capital do Brasil ? " )
     leia(Resposta)
     
     se Resposta = "Brasília" entao
      escreva(" Resposta Correta! Brasília é a Capital. ")
       senao
        escreva(" Resposta incorreta! A Capital é Brasília. ")
     fimse

fimalgoritmo
