algoritmo "Divisivel por 3 e 5"
//  Fazer um algoritmo que leia um valor e verifique se é divisível por 3 e 5 ao mesmo tempo

var

  Num:inteiro
  
inicio
   escreva(" Informe um Número: ")
   leia(Num)
   
   se (Num % 3 = 0) e (Num % 5 = 0) entao
     escreval(" O Número é divisivel por 3 epor 5 ao mesmo tempo ")
      senao
      escreval(" O Número não é divisivel por 3 e 5 ao mesmo tempo ")

   fimse
fimalgoritmo
