algoritmo "Maior ou Menor de idade"
// Fazer um algoritmo que leia a idade de uma pessoa e informe se é maior de idade ou não

var
  Nome:caracter
  Idade:real

inicio
  escreva(" Informe o Nome: ")
  leia(Nome)
  escreva(" Informe a Idade: ")
  leia(Idade)
  
  escreval("")
  
  se Idade >= 18 entao
    escreval(" Maior de Idade ")
    senao
    escreval(" Menor de Idade ")

    
  fimse
fimalgoritmo
