algoritmo "Quadrado Retângulo"
//  Fazer um algoritmo que leia o valor da base e altura de um retângulo e retorne se esse retângulo é também quadrado

var

 Base:real
 Altura:real
 
inicio

   escreva(" Informe a base: ")
   leia(Base)
   escreva(" Informe a Altura: ")
   leia(Altura)
   
   se Base = Altura entao
       escreval(" Quadrado ")
       senao
       escreval(" Retângulo ")
       
   fimse
fimalgoritmo
