algoritmo "Exe2-"

 // 2 - fazer algoritmo para nome, endereço, telefone
 
var
  Nome:caracter
  Tel:caracter
  Endereco:caracter
  
inicio
   escreva(" Digite seu nome: ")
   leia(Nome)
   escreva(" Digite seu telefone: ")
   leia(Tel)
   escreva(" Digite seu endereco: ")
   leia(Endereco)
   limpatela
   escreval("*****Informações*****")
   escreval("nome: ", Nome)
   escreval("telefone: ", Tel)
   escreval("endereco: ", Endereco)

fimalgoritmo
