algoritmo "Exe6-"

// fazer um algoritmo para propriedades do retângulo

var
 Base, Altura, Area, Perimetro, Diagonal:real

inicio
escreva("Digite a base do retangulo: ")
leia(Base)
escreva("Digite a altura do retangulo: ")
leia(Altura)

Perimetro <- 2 * (Base + Altura)
Area <- Base + Altura
diagonal <- (base^2 + altura^2)

escreval("a - perimetro: ",Perimetro)
escreval("b - area: ",Area)
escreval("c - diagonal: ",Diagonal)
fimalgoritmo
