algoritmo "100 pessoas e retorne a média dessas idades"
// Fazer um programa que leia a idade de 100 pessoas e retorne a média dessas idades.

var

Idade:inteiro
  Media:real
  SomaIdade:real
  i:inteiro
inicio
   para i de 1 ate 100 faca
       escreva(" Informe a idade: ")
       leia(Idade)

        SomaIdade <- SomaIdade + Idade


   fimpara


  Media <- SomaIdade /100

 escreval("-------MEDIA DE IDADE -------")
 escreval(" A Media de idade é: ", Media)

fimalgoritmo

