algoritmo "567 alturas"
// Faça um programa que leia 567 alturas e retorne a média das alturas.
var

   Altura:real
   i:inteiro
   SomaAltura:real
   Media:real
   
   
inicio

    Para i de 1 ate 567 faca
      Escreva(" Digite a altura: ")
      leia(Altura)
      somaAltura <- somaAltura + Altura
      
      
    fimpara
    
        Escreval("A média das alturas é: ", somaAltura / 567)




fimalgoritmo
