algoritmo "matriz 3X3 de tipo Lógico"
 // Faça um algoritmo com uma matriz 3X3 de tipo Lógico
  //Respondendo VERDADEIRO OU FALSO para a seguinte pergunta
  //Gostaram de Lógica de programação?

var

  MatLog  :  vetor[1..3,1..3] de logico
  Lin, Col:  inteiro
  ind     :  inteiro

inicio

   para Lin de 1 ate 3 faca
    para Col de 1 ate 3 faca
    
    
    
    fimpara
   fimpara


fimalgoritmo

